### ISSUE TITLE
v1.21

### ISSUE THREAD

**Issue by karlglazebrook** [PDLPorters/extutils-f77#3] opened 2018-11-24 08:02 UTC
Are we all happy to do a v1.21 release to CPAN?

There have been a few minor changes since the last release in May 2016

**Comment by mohawk2** [comment] 2018-11-24 19:01
YES! Please :-)

(Please also take into account my suggestion on #2, which will make maintaining that bit easier)

**Comment by karlglazebrook** [comment] 2018-11-25 02:55
All OK.

Released to CPAN. Wow, PAUSE is still so Web 1995!

Karl

**Comment by mohawk2** [comment] 2018-11-25 03:11
It is! But there is an easier way:

```
cpanm CPAN::Uploader
# configure your login details
cpan-upload ExtUtils-*
```

See https://metacpan.org/pod/release/RJBS/CPAN-Uploader-0.103013/bin/cpan-upload#CONFIGURATION for more.

**Comment by karlglazebrook** [comment] 2018-11-25 03:25
OK next time!

**Comment by karlglazebrook** [comment] 2018-12-01 06:06
Hi PDL-general

So I released a new version of ExtUtils::F77 to CPAN with minor tweaks (via PAUSE, see below). However this seems to have resulted in the deletion of the entire module!

(Searching CPAN does not find it)

Does anyone have a clue what might have happened? (Note the testing link below seems to generate a lot of red, maybe that is something to do with it)

Karl



> The uploaded file
> 
>    ExtUtils-F77-1.21.tar.gz
> 
> has entered CPAN as
> 
>  file: $CPAN/authors/id/K/KG/KGB/ExtUtils-F77-1.21.tar.gz
>  size: 12229 bytes
>   md5: c2dfd4f5bc6c57ceb7eb25a669749183
>  sha1: b9777889785fc4a3df660e1e41e5f742099772c1
> 
> CPAN Testers will start reporting results in an hour or so:
> 
>  http://matrix.cpantesters.org/?dist=ExtUtils-F77 <http://matrix.cpantesters.org/?dist=ExtUtils-F77>
> 
> Request entered by: KGB (Karl Glazebrook)
> Request entered on: Sun, 25 Nov 2018 02:52:36 GMT
> Request completed:  Sun, 25 Nov 2018 02:53:02 GMT
> 
> Thanks,
> -- 
> paused, v1049

**Comment by mohawk2** [comment] 2018-12-01 18:44
It seems you're right, and it's been deleted off main CPAN. It's still available on "BackPAN", so e.g. this works: `cpanm ExtUtils::F77@1.21`

However, because it's missing from the main index, `cpanm ExtUtils::F77` fails. The normal reason for that is someone has deleted it using the PAUSE interface. I will inquire whether anything else might have happened.

**Comment by Grinnz** [comment] 2018-12-01 18:55
Hello,    ExtUtils-F77-1.21 has been deleted from CPAN which also removed it from the index. Normally the only way a release can be deleted from CPAN is by its uploader in the PAUSE interface, or via a cleanup script like https://metacpan.org/pod/App::PAUSE::cleanup. I'm not sure how this release got deleted but I would recommend uploading a new version 1.22 rather than reusing 1.21.

**Comment by mohawk2** [comment] 2018-12-01 19:06
We should probably make a 1.22 immediately, so it's back in the index. Then we should investigate why cpantesters is showing 84% failures: https://www.cpantesters.org/distro/E/ExtUtils-F77.html?oncpan=1&distmat=1&version=1.21&grade=3

**Comment by mohawk2** [comment] 2018-12-01 19:10
In fact, before re-releasing let me make the tests a bit more communicative when they do fail.

**Comment by karlglazebrook** [comment] 2018-12-01 23:49
Yeah, I am suspecting the reason for all the fails is that none of the testers have fortran installed. Not sure the best way to handle that, clearly not having fortran installed means you can’t test it properly!

Karl

**Comment by mohawk2** [comment] 2018-12-01 23:59
@karlglazebrook The way to handle a lack of Fortran would be to refuse to install, which would then cause an NA result, which is perfectly fine - this would be done in `Makefile.PL`, using the new `os_unsupported` function visible at https://perldoc.pl/ExtUtils::MakeMaker#Other-Handy-Functions . With the information provided by the updated tests and code in #5 we will know for sure! (Hopefully)

**Comment by karlglazebrook** [comment] 2018-12-02 00:01
That would be a useful patch

Though I’d have to install a VM to test...

**Comment by mohawk2** [comment] 2018-12-02 00:12
I'd suggest leaving the `os_unsupported` thing for now, and either merge #5 or not, but release a 1.22 fairly soon?

**Comment by karlglazebrook** [comment] 2018-12-02 00:19
Well I am still waiting to hear what the problem was

- Karl

**Comment by mohawk2** [comment] 2018-12-02 00:57
The problem is most likely that someone deleted 1.21 off CPAN, using the PAUSE interface. This is a process that queues the deletion for (I believe) 3 days, then executes. Is it possible you accidentally deleted it 3 days ago?

**Comment by karlglazebrook** [comment] 2018-12-02 01:07
Why would that delete all the old versions?

Will check PAUSE

- Karl

**Comment by Grinnz** [comment] 2018-12-02 01:27
It would not (unless you also queued the older versions you uploaded for deletion); in fact version 1.20 is still on CPAN, but is unindexed because the indexed version was 1.21, so it would need manual reindexing in the PAUSE interface to regain its indexed status. Uploading a new 1.22 would also fix that issue.

**Comment by shawnlaffan** [comment] 2018-12-02 05:14
The indexing problem looks like the same root cause as https://github.com/jlapeyre/PDL-Fit-Levmar/issues/3

Indexing needs a package file, even if skeletal, at ```lib/ExtUtuls/F77.pm```

The example here is relevant, even if for a different root cause:  https://metacpan.org/about/missing_modules#isthedistributionpodonlywithnopackage

WRT its removal from the cpan index, my guess is that the new upload superseded the previous index entry, resulting in its removal from the index.

**Comment by Grinnz** [comment] 2018-12-02 06:19
That would not affect the currently indexed release, and certainly would not delete it from CPAN.

**Comment by mohawk2** [comment] 2018-12-02 06:27
Additionally, the directory and file layout of EU::F77 has not changed in a long time.

**Comment by karlglazebrook** [comment] 2018-12-02 06:38
Well let’s try a v1.22 release:

This is the tarball's contents:

/GIT/extutils-f77: tar tfz ExtUtils-F77-1.22.tar.gz 
ExtUtils-F77-1.22/
ExtUtils-F77-1.22/CHANGES
ExtUtils-F77-1.22/MANIFEST
ExtUtils-F77-1.22/F77.pm
ExtUtils-F77-1.22/t/
ExtUtils-F77-1.22/README
ExtUtils-F77-1.22/COPYING
ExtUtils-F77-1.22/META.yml
ExtUtils-F77-1.22/Makefile.PL
ExtUtils-F77-1.22/META.json
ExtUtils-F77-1.22/t/require.t

Below is the PAUSE upload notification:

I did tidy up files on PAUSE last time, but I thought this was just a staging area?

Karl

-------------------------


The uploaded file

   ExtUtils-F77-1.22.tar.gz

has entered CPAN as

 file: $CPAN/authors/id/K/KG/KGB/ExtUtils-F77-1.22.tar.gz
 size: 12260 bytes
  md5: 3606b0dc59320c62bb866be93e992ae8
 sha1: 9e1d576d99a2d85c7ebfd021d279c7f249854f83

CPAN Testers will start reporting results in an hour or so:

 http://matrix.cpantesters.org/?dist=ExtUtils-F77 <http://matrix.cpantesters.org/?dist=ExtUtils-F77>

Request entered by: KGB (Karl Glazebrook)
Request entered on: Sun, 02 Dec 2018 06:34:49 GMT
Request completed:  Sun, 02 Dec 2018 06:35:07 GMT

Thanks,
-- 
paused, v1049

**Comment by mohawk2** [comment] 2018-12-02 06:40
That "tidying up" was what was referred to above as "deleting": you deleted the file off CPAN ;-)

**Comment by karlglazebrook** [comment] 2018-12-02 06:42
I got a message somewhere along the line that authors were encouraged to delete old files off of PAUSE.  As I said I thought the PAUSE upload space was just a staging area, but you are saying it’s not and if files are deleted from there then they get removed from CPAN?

Ah! Oops…

Karl

**Comment by mohawk2** [comment] 2018-12-02 06:46
I very much am saying that. It's not a staging area. The wording probably needs improving!

**Comment by shawnlaffan** [comment] 2018-12-02 07:21
Well that's me standing corrected about the root cause.  1.22 is visible on metacpan at https://metacpan.org/release/KGB/ExtUtils-F77-1.22

**Comment by Grinnz** [comment] 2018-12-02 07:50
The new release has been successfully indexed. https://cpanmeta.grinnz.com/packages#=ExtUtils::F77

The PAUSE interface is just an interface (and indexer); the files only go to CPAN.

**Comment by karlglazebrook** [comment] 2018-12-02 11:53
Hooray! Well I learned a lesson. Thanks everyone !

- Karl

**Comment by mohawk2** [comment] 2018-12-02 14:26
@karlglazebrook Great! I will close this. Now we have a working version on CPAN again, the immediate pressure is off. Want to look at maybe merging and dev-releasing #5?

**Closed as completed** 2018-12-02 14:26 UTC
